---
- name: restart elasticsearch
  listen: restart elasticsearch
  community.docker.docker_compose_v2:
    project_src: "{{ elk_compose_dir }}"
    services:
      - elasticsearch
    state: restarted

- name: restart logstash
  listen: restart logstash
  community.docker.docker_compose_v2:
    project_src: "{{ elk_compose_dir }}"
    services:
      - logstash
    state: restarted

- name: restart kibana
  listen: restart kibana
  community.docker.docker_compose_v2:
    project_src: "{{ elk_compose_dir }}"
    services:
      - kibana
    state: restarted

- name: restart elastic-agent
  listen: restart elastic-agent
  community.docker.docker_compose_v2:
    project_src: "{{ elk_compose_dir }}"
    services:
      - elastic-agent
    state: restarted

- name: remove kibana token cache
  listen: remove kibana token cache
  ansible.builtin.file:
    path: "{{ kibana_token_file }}"
    state: absent