# ===== Start remaining containers =====
- name: Ensure Kibana, Logstash and Elastic Agent are running
  community.docker.docker_compose_v2:
    project_src: "{{ elk_compose_dir }}"
    services:
      - kibana
      - logstash
      - elastic-agent
    state: present

- name: Wait for Kibana to respond 200 or 401
  ansible.builtin.uri:
     url: "http://localhost:5601"
     method: GET
     status_code: [200,401]
  register: kibana_status
  retries: 30
  delay: 5
  until: kibana_status.status in [200,401]
